[package]
name = "ast-explorer"
version = "0.1.0"
authors = ["Nick Spain <nicholas.spain@stileeducation.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prometheus-parser = "0.4.0"
